name: Tizen app build

on:
  push:
  pull_request:
    branches: [ main ]

env:
  TIZEN_STUDIO_URL: "http://download.tizen.org/sdk/Installer/tizen-studio_5.6/web-cli_Tizen_Studio_5.6_ubuntu-64.bin"

jobs:
  native:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: ['TextClassification', 'OrientationDetection']
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
    - name: Install Tizen Studio
      shell: bash
      run: |
        wget -nc -O ${{ github.workspace }}/installer $TIZEN_STUDIO_URL
        chmod a+x ${{ github.workspace }}/installer
        bash ${{ github.workspace }}/installer --accept-license ${{ github.workspace }}/tizen-studio
    - name: Build Tizen native application
      shell: bash
      run: |
        export PATH=$PATH:${{ github.workspace }}/tizen-studio/tools/ide/bin
        tizen build-cs -- ${{ github.workspace }}/Tizen.NET/${{ matrix.app }}
        mkdir -p ${{ github.workspace }}/Tizen.NET/${{ matrix.app }}/tpk
        find . -name '*.tpk' -exec mv {} ${{ github.workspace }}/Tizen.NET/${{ matrix.app }}/tpk \;
    - name: Upload tpk package
      uses: actions/upload-artifact@v4
      with:
        name: tizen_cs_${{ matrix.app }}
        path: ${{ github.workspace }}/Tizen.NET/${{ matrix.app }}/tpk
